generationzero/urls.py
from django.conf.urls import (url, include)
# from django.contrib import admin
from magazine.admin import admin_site
from magazine import urls as magazine_urls


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^admin/', admin_site.urls),
    url(r'', include(magazine_urls)),
    url('^markdown/', include( 'django_markdown.urls')),
]

magazine/urls.py
from django.conf.urls import url
from django.views.generic.dates import ArchiveIndexView

from magazine.models import Entry
from magazine.views import (HomePageView, IssueView, IssueListView,
        EntryDetailView)


urlpatterns = [
    url(r'^$',
        HomePageView.as_view(),
        name="home_page"),

    url(r'^issue/$', IssueListView.as_view(), name="issue_list"),
    url(r'^issue/(?P<issue_slug>[\w-]+)/$', IssueView.as_view(), name="issue"),

    # entry in issue
    # url(r'^issue/(?P<issue_slug>[\w-]+)/(?P<entry_slug>[\w-]+)/$',
    #     EntryDetailView.as_view(),
    #     name="entry_in_issue"),

    url(r'^category/(?P<category_slug>[\w-]+)/$',
        # CategoryView.as_view(),
        HomePageView.as_view(),
        name="category"),

    # entry in category
    # url(r'^category/(?P<category_slug>[\w-]+)/(?P<entry_slug>[\w-]+)/$',
    #     EntryDetailView.as_view(),
    #     name="entry_in_category"),

    # just a single entry
    url(r'^entry/(?P<entry_slug>[\w-]+)/$',
        EntryDetailView.as_view(),
        name="entry"),

    # TODO
    # url(r'^archive/$',
    #     ArchiveIndexView.as_view(model=Entry, date_field="created_at"),
    #     name="entry_archive"),
]

magazine/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django_markdown.models import MarkdownField
from django.utils import timezone


class Issue(models.Model):
    """An issue is a themed collection of blog entries with accompanying text"""
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    number = models.IntegerField()
    introduction = models.TextField()
    # TODO make this generic?
    well_image = models.CharField(
        max_length=200,
        blank=True,
        help_text="Image to fill this issue's well (higher "+
                  "priority than 'well text').")
    well_text = models.TextField(
        blank=True,
        help_text="Text to fill this issue's well (if blank, 'issue "+
                  "content' will be used).")
    created_at = models.DateTimeField(default=timezone.now)
    modified_at = models.DateTimeField(auto_now=True)
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class Category(models.Model):
    """A category is another collection of blog entries."""
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    created_at = models.DateTimeField(default=timezone.now)
    modified_at = models.DateTimeField(auto_now=True)
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category', kwargs={'category_slug': self.slug})


class MainCategory(models.Model):
    """A main-category is one which the user can browse in the top menu. If
    there are none specified, then the categories are ordered by number of
    entries.
    """
    category = models.OneToOneField(Category,
        help_text="This category will appear in the header-menu. If there are "
        "no main-categories then the most popular ones will be displayed.")

    def __str__(self):
        return self.category.title


class Entry(models.Model):
    """An single magazine entry."""
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    content = MarkdownField()
    well_image = models.CharField(
        max_length=200,
        blank=True,
        help_text="Image to fill this entry's well (higher "+
                  "priority than 'well text').")
    well_text = models.TextField(
        blank=True,
        help_text="Text to fill this entry's well (if blank, 'entry "+
                  "content' will be used).")
    issue = models.ForeignKey(Issue, blank=True, null=True, default=None)
    categories = models.ManyToManyField(Category)
    created_by = models.ForeignKey(User)
    created_at = models.DateTimeField(default=timezone.now)
    modified_at = models.DateTimeField(auto_now=True)
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def categories_display(self):
        # This is DB heavy
        return ', '.join(map(str, self.categories.all()))
    categories_display.short_description = 'Categories'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    {% block meta %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock meta %}

    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <!--[if lte IE 8]>
      <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
      <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->
    <script type="text/javascript" src="{% static 'js/jquery-1.12.0.min.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/masthead.js' %}" charset="utf-8"></script>
    {% endblock css %}

    <title>Generation Zero{% block title_suffix %}{% endblock title_suffix %}</title>
    {% endblock head %}
  </head>
  <body>
    {% block body %}

    {% if not category %}
    <div id="masthead_container">
      <div id="masthead">
        <img src="{% static 'img/branding.png' %}">
      </div>
    </div>
    {% endif %}

    <div id="header_container">

      <div id="branding">
        <a href="{% url 'home_page' %}">
          <img src="{% static 'img/branding.png' %}" id="main-logo-small">
        </a>
      </div>

      <div id="header">
        <div id="navigation">
          <ul>
            {% for category in main_category_list %}
            <li>
              <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
            </li>
            {% endfor %}
            <li>
              <a href="{% url 'issue_list' %}">Issues</a>
            </li>
          </ul>
        </div>
      </div>

      <div id="menu-burger-control">
        <a href="#" id="menu-burger-open">&#9776;</a>
        {% comment %}
        <a href="#" id="menu-burger-close">&#x00d7;</a>
        {% endcomment %}
      </div>

    </div>

    <div id="header_mobile">
      <div id="branding_mobile">
        <a href="{% url 'home_page' %}">
          <img src="{% static 'img/branding.png' %}" id="main-logo-small">
        </a>
      </div>
    </div>

    {% include "drop_down_menu.html" %}

    <div id="main_content_container">
      {% block content_container %}
      <div id="main_content">
        {% block content %}
        {# here is where the actual content goes #}
        {% endblock content %}
        <div class="clear"></div>
      </div>
      {% endblock content_container %}
    </div>

    <footer class="footer">
        <p>Copyright © 2016 &dash; {% now "Y" %} Generation Zero</p>
    </footer>

    {% endblock body %}
  </body>
  {% block js %}
  {% endblock js %}

  {% include "base.js.html" %}

  <!-- Google Analytics -->
  <script>
  if ({{ debug|yesno:"false,true"}}) {
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-91746360-1', 'auto');
    ga('send', 'pageview');
  }
  </script>

</html>

templates/base.js.html
<script type="text/javascript">
var GenerationZero = {
  menu_dropdown_is_visible: false,
    slide_opts: {duration: 400, easing: 'swing'},
};

GenerationZero.menu_dropdown_hide = function() {
    $("#menu-dropdown").slideUp(GenerationZero.slide_opts);
    GenerationZero.menu_dropdown_is_visible = false;
};

GenerationZero.menu_dropdown_show = function() {
    $("#menu-dropdown").slideDown(GenerationZero.slide_opts);
    GenerationZero.menu_dropdown_is_visible = true;
};

// event handlers
$('#menu-burger-control a').click(function() {
  if (GenerationZero.menu_dropdown_is_visible) {
    GenerationZero.menu_dropdown_hide();
  } else {
    GenerationZero.menu_dropdown_show();
  }
});
</script>

templates/category.html
{% extends "base.html" %}

{% block title_suffix %}
/ {{ category.title }}
{% endblock title_suffix %}

{% block content %}

{# breadcrumbs #}
<a href="{% url 'home_page' %}">Generation Zero</a> /

<h2>{{ category.title }}</h2>
<ul>
  {% for entry in entry_list %}
  <li><a href="{% url 'entry_in_category' category_slug=category.slug entry_slug=entry.slug %}">{{ entry.title }}</a></li>
  {% empty %}
  <li>No entries</li>
  {% endfor %}
</ul>

{% endblock content %}

templates/drop_down_menu.html
{% load static %}

<div id="menu-dropdown" class="pure-g hide">
  <div id="menu-dropdown-categories" class="pure-u-1-2">
    <div class="menu-dropdown-title">
      Categories
    </div>
    <div class="pure-g menu-dropdown-category-list">
      {% for category in category_list %}
      <div class="pure-u-1-4 menu-dropdown-category-list-item">
        <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
      </div>
      {% empty %}
      <div>No categories</div>
      {% endfor %}
    </div>
  </div>
  <div id="menu-dropdown-contact" class="pure-u-1-4">
    <div class="menu-dropdown-title">
      Contact
    </div>
    <p id="menu-dropdown-contact-email">
      <a href="mailto:jacob_ormrod@hotmail.com">jacob_ormrod@hotmail.com</a>
    </p>
    <p>
      For submissions, please contact us via email or Facebook.
    </p>
  </div>
  <div id="menu-dropdown-social"class="pure-u-1-4">
    <div class="menu-dropdown-title">
      Social
    </div>
    <ul>
      <li>
        <a href="https://www.facebook.com/GenerationZeroMagazine/"
          class="sociallink">
          <img src="{% static 'img/social/Sm_Icons_Facebook.png' %}"
            alt="GenerationZero Facebook" id="facebook-link">
        </a>
      </li>
      <li>
        <a href="https://twitter.com/GenZeroMag" class="sociallink">
          <img src="{% static 'img/social/Sm_Icons_1_Twitter.png' %}"
            alt="GenerationZero Twitter" id="twitter-link">
        </a>
      </li>
      <li>
        <a href="https://www.instagram.com/generationzer0magazine/"
          class="sociallink">
          <img src="{% static 'img/social/Sm_Icons_Instagram.png' %}"
            alt="GenerationZero Instagram" id="instagram-link">
        </a>
      </li>
      {% comment %}
      <li>
        <a href=""
          class="sociallink">
          <img src="{% static 'img/social/Sm_Icons_pinterest.png' %}"
            alt="GenerationZero Pinterest" id="pinterest-link">
        </a>
      </li>
      <li>
        <a href=""
          class="sociallink">
          <img src="{% static 'img/social/Sm_Icons_youtube.png' %}"
            alt="GenerationZero YouTube" id="youtube-link">
        </a>
      </li>
      {% endcomment %}
    </ul>
  </div>
</div>

templates/entry_archive.html
{# TODO #}
<ul>
    {% for entry in latest %}
        <li>{{ entry.pub_date }}: {{ entry.title }}</li>
    {% endfor %}
</ul>

templates/issue.html
{% extends "base.html" %}

{% block title_suffix %}
/ {{ issue.title }}
{% endblock title_suffix %}

{% block content %}

{# breadcrumbs #}
<a href="{% url 'home_page' %}">Generation Zero</a> /

<h2>{{ issue.title }}</h2>
<div class="grid">
    {% for entry in entry_list %}
      <div class="grid_item">
        <img src="/static/img/branding.png">
        <a href="{% url 'entry_in_issue' issue_slug=issue.slug entry_slug=entry.slug %}">{{ entry.title }}</a>
      </div>
    {% empty %}
      <div>No entries</div>
    {% endfor %}
</div>
<script type="text/javascript">
  $(document).ready(function(){
    console.log("document ready");
    var grid = $('.grid').masonry({
      itemSelector: '.grid_item',
      transitionDuration: 0
    });
  });
</script>
{% endblock content %}